from __future__ import annotations

import secrets
from pathlib import Path

from kdr_installer.provider_config import update_runtime_settings


def generate_pairing_token() -> str:
    return secrets.token_urlsafe(32)


def build_runtime_env(*, token: str, telemetry_enabled: bool) -> str:
    if not token or any(ch.isspace() for ch in token):
        raise ValueError("pairing token is invalid")
    enabled = "true" if telemetry_enabled else "false"
    return (
        "# Generated by the KDR installer. Do not commit this file.\n"
        f"KDR_MOBILE_TELEMETRY_ENABLED={enabled}\n"
        f"KDR_MOBILE_API_TOKEN={token}\n"
    )


def write_runtime_env(root: Path, *, token: str, telemetry_enabled: bool) -> Path:
    if not token or any(ch.isspace() for ch in token):
        raise ValueError("pairing token is invalid")
    return update_runtime_settings(
        root,
        {
            "KDR_MOBILE_TELEMETRY_ENABLED": "true" if telemetry_enabled else "false",
            "KDR_MOBILE_API_TOKEN": token,
        },
    )


def tailscale_serve_args() -> list[str]:
    return [
        "tailscale",
        "serve",
        "--bg",
        "--set-path=/api/v1/mobile/",
        "http://127.0.0.1:8000/api/v1/mobile/",
    ]
