from __future__ import annotations

from pathlib import Path

_RUNTIME_KEYS = (
    "KDR_MOBILE_TELEMETRY_ENABLED",
    "KDR_MOBILE_API_TOKEN",
    "KDR_PLAY_DISCOVERY_PROVIDER",
    "KDR_SERPAPI_API_KEY",
    "KDR_TALORDATA_API_KEY",
    "KDR_TALORDATA_SERP_ENDPOINT",
)


def _runtime_path(root: Path) -> Path:
    return root / ".kdr" / "runtime.env"


def read_runtime_settings(root: Path) -> dict[str, str]:
    path = _runtime_path(root)
    if not path.is_file():
        return {}
    result: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        if key in _RUNTIME_KEYS:
            result[key] = value
    return result


def _validate_value(key: str, value: str) -> str:
    normalized = value.strip()
    if not normalized or any(ch in normalized for ch in "\r\n\x00"):
        raise ValueError(f"{key} contains an invalid value")
    return normalized


def update_runtime_settings(root: Path, updates: dict[str, str | None]) -> Path:
    unknown = set(updates) - set(_RUNTIME_KEYS)
    if unknown:
        raise ValueError(f"unsupported runtime setting: {sorted(unknown)[0]}")
    settings = read_runtime_settings(root)
    for key, value in updates.items():
        if value is None or value == "":
            settings.pop(key, None)
        else:
            settings[key] = _validate_value(key, value)

    path = _runtime_path(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(".tmp")
    lines = ["# Generated by the KDR installer. Do not commit this file."]
    for key in _RUNTIME_KEYS:
        if key in settings:
            lines.append(f"{key}={settings[key]}")
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        temporary.chmod(0o600)
    except OSError:
        pass
    temporary.replace(path)
    return path


def configure_play_provider(root: Path, *, provider: str, api_key: str | None) -> Path:
    normalized = provider.strip().lower()
    if normalized not in {"auto", "talordata", "serpapi", "public_html"}:
        raise ValueError("provider must be auto, talordata, serpapi, or public_html")
    if normalized in {"talordata", "serpapi"} and not api_key:
        raise ValueError(f"{normalized} requires an API key")

    updates: dict[str, str | None] = {"KDR_PLAY_DISCOVERY_PROVIDER": normalized}
    if normalized == "talordata":
        updates["KDR_TALORDATA_API_KEY"] = api_key
    elif normalized == "serpapi":
        updates["KDR_SERPAPI_API_KEY"] = api_key
    return update_runtime_settings(root, updates)
